### ISSUE TITLE
LogWriter.LogWriter.WriteToLog does'nt work

### ISSUE THREAD

**Issue by SwimmerRcd** [dbaaron/log-writer#1]
I build a sample to run it , but the methond "LogWriter.LogWriter.WriteToLog" does'nt work. I debug it and found that because in  method "LogWriter.LogWriter.FlushLogToFile" , the  object "StreamWriter writer" dosen't closed.  so you should add "writer.close" after "writer.WriteLine" in method "LogWriter.LogWriter.FlushLogToFile" like this below:
``               
                //
                FileStream stream = new FileStream(path, FileMode.Append, FileAccess.Write);
                StreamWriter writer = new StreamWriter(stream);

                // Log to file
                writer.WriteLine(String.Format("{0}\t{1}", entry.GetTime(), entry.GetMessage()));
                writer.Close();  // <---------- add this

                stream.Close();
``

**Comment by dbaaron** [comment]
I went ahead and wrapped the stream writer in a using statement so it will dispose after writing the line to the log, closing this issue,

**Comment by SwimmerRcd** [comment]
wrap stream writer in a using statement? but how? like this?
``using (LogWriter.LogWriter logger = LogWriter.LogWriter.GetInstance)
            {
                LogWriter.LogWriter.WriteToLog("hi,log");
            }
but it can't pass the compile check

**Comment by dbaaron** [comment]
`using (var writer = new StreamWriter(stream)) { }`

See change: https://github.com/dbaaron/log-writer/commit/b0378c66a9931c9e0f6eb2b9660133ad00ca3f1e
